### ISSUE TITLE
Adding new attributes to types is a bad idea

### ISSUE THREAD

**Issue by BGWoodward** [cvisionai/tator#198] opened 2020-09-07 13:24 UTC
Despite the admin interface allowing it, there are a host of issues with adding new attributes to types after they have been created. The logic does not currently exist to do mapping or migration properly of default values, and there are a myriad of issues relating to PATCH,POST,GET schema inconsistencies that result in errors in the javascript, and inability to upload files via tator-py. A suggestion is to disable this (would be unfortunate), or implement more robust logic to trigger the proper steps to handle modified types.

**Comment by jrtcppv** [comment] 2020-09-07 13:25
Duplicate of https://github.com/cvisionai/tator/issues/189

**Comment by henxing** [comment] 2020-12-29 18:36
Fixed by 63ff3651b8f8c870b4f99f05f7019132b7021361

**Closed by henxing** 2020-12-29 18:36 UTC
Labels: bug
