### ISSUE TITLE
Section logic can  bomb out and show no sections

### ISSUE THREAD

**Issue by bctcvai** [cvisionai/tator#1655] opened 2024-04-29 17:38 UTC
If there is an error with section topology, the section browser can bomb out and show no sections. Ideally we'd display as many valid sections as possible. 

If possible, showing "messed up sections" somewhere in the UI seems like a good idea, if it isn't a big lift.

**Comment by marktaipan-cvisionai** [comment] 2024-04-29 17:53
Duplicate of #1650 - going to close this once since the related PR references #1650

**Closed by marktaipan-cvisionai** 2024-04-29 17:53 UTC
Labels: bug
