### ISSUE TITLE
build of tator-image on ubunutu 18.04 LTS fails due to setup-tool dependency

### ISSUE THREAD

**Issue by Kilill** [cvisionai/tator#23] opened 2019-11-06 01:30 UTC
Building on kubuntu 18.04 LTS fails.
kubernets-client/python as a requirement on google-auth>=1.0.1 this leads to google-auth 7.0.1 beeing pulled in, but google-auth requires setuptools 4,0 which is not available for Ubuntu 18.4 (it is in 19) , I ended up forking the kubernets-clients/python and changing the google-auth requirement in requirements.txt from >=1.0.1 to ==1.6.2 to get the build to go  through. It might be that 1.6.3 works as well.

**Comment by Kilill** [comment] 2019-11-06 01:59
But even after fixing that is still fails wen building marshal-image:
`Error response from daemon: Dockerfile parse error line 7: COPY requires at least two arguments, but only one was provided. Destination could not be determined.
`
just adding a '/' to the COPY command gets it to fail on the next line:
`Error response from daemon: Dockerfile parse error line 8: unknown instruction: -PY3-NONE-ANY.WHL`

**Comment by Kilill** [comment] 2019-11-06 02:05
And sorry for the duplicate first error , could not find the first one (#22) for some reason so sought i fumbled it and failed to submit it.. and it turns out it was fixed and closed, i must say that was fast indeed

**Comment by jrtcppv** [comment] 2019-11-06 02:50
No problem at all! Since this is a duplicate of #22 I will go ahead and close this one as well.

**Closed by jrtcppv** 2019-11-06 02:50 UTC
