### ISSUE TITLE
Something weird visually is happening on track seek (track to track)

### ISSUE THREAD

**Issue by jrtcppv** [cvisionai/tator#4] opened 2019-09-15 14:49 UTC
Looks like it is drawing the box before the frame jump. Probably more noticable depending on computer speed / network speed. https://cvision.tatorapp.com/1/annotation/313841?attribute=tator_user_sections::Winter%202019%20Survey%20Processed%20Tow%205

**Comment by bctcvai** [comment] 2019-11-13 02:52
Duplicate of #14

**Closed by bctcvai** 2019-11-13 02:52 UTC
Labels: bug, medium priority
