### ISSUE TITLE
Display the invitation URL in project settings

### ISSUE THREAD

**Issue by marktaipan-cvisionai** [cvisionai/tator#808] opened 2022-08-11 19:34 UTC
When inviting a user to a Tator organization, the dialog window contains a link. However, that link is not visible after closing the confirmation modal. It would be helpful to display the link in the invitation entry (or at least corresponding invitation token).

**Comment by bctcvai** [comment] 2022-08-18 01:11
Is this a dupe of #758?

**Closed** 2022-09-19 18:35 UTC
