### ISSUE TITLE
*File endpoints should take a bucket parameter

### ISSUE THREAD

**Issue by jrtcppv** [cvisionai/tator#1881] opened 2024-11-21 20:30 UTC
This would allow adding a file to a media object from a bucket other than the one registered as default for a project. This is useful in, for example, cross-deployment imports.

**Comment by bctcvai** [comment] 2024-12-13 13:54
This is a dupe of https://github.com/cvisionai/tator/issues/1630

**Comment by jrtcppv** [comment] 2024-12-19 17:17
This is not a dupe, *File endpoints do not require an upload necessarily.

**Closed** 2024-12-20 21:45 UTC
